caption: 'ğŸ’–ğŸ¥°Ğ˜Ğ©Ğ•Ğ¢  ĞœĞ£Ğ–Ğ§Ğ˜ĞĞ£ ğŸ‘‡

  ĞšĞĞĞ¢ĞĞšĞ¢Ğ« Ğ”Ğ•Ğ’Ğ£Ğ¨ĞšĞ˜ (@loves_fly1) âœ¨

  ĞŸĞµÑ€ĞµÑ…Ğ¾Ğ´Ğ¸ Ğ¸ Ğ¿Ğ¸ÑˆĞ¸ Ğ¿Ğ¾ ÑÑÑ‹Ğ»ĞºĞµ Ğ² Ğ¿Ñ€Ğ¾Ñ„Ğ¸Ğ»Ğµ

  '
is_easter_egg: false
is_feed: true
is_story: false
